// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIMDMRisksOperRiskMessWindow UIMDMRisksOperRiskMessWindow
        {
            get
            {
                if ((this.mUIMDMRisksOperRiskMessWindow == null))
                {
                    this.mUIMDMRisksOperRiskMessWindow = new UIMDMRisksOperRiskMessWindow();
                }
                return this.mUIMDMRisksOperRiskMessWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMDMRisksOperRiskMessWindow mUIMDMRisksOperRiskMessWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMDMRisksOperRiskMessWindow : WinWindow
    {
        
        public UIMDMRisksOperRiskMessWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIItemComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new UIItemComboBox(this);
                }
                return this.mUIItemComboBox;
            }
        }
        
        public UIItemHyperlink UIItemHyperlink
        {
            get
            {
                if ((this.mUIItemHyperlink == null))
                {
                    this.mUIItemHyperlink = new UIItemHyperlink(this);
                }
                return this.mUIItemHyperlink;
            }
        }
        
        public UIItem11Hyperlink UIItem11Hyperlink
        {
            get
            {
                if ((this.mUIItem11Hyperlink == null))
                {
                    this.mUIItem11Hyperlink = new UIItem11Hyperlink(this);
                }
                return this.mUIItem11Hyperlink;
            }
        }
        
        public UIItemCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new UIItemCell(this);
                }
                return this.mUIItemCell;
            }
        }
        
        public UIItemHyperlink1 UIItemHyperlink1
        {
            get
            {
                if ((this.mUIItemHyperlink1 == null))
                {
                    this.mUIItemHyperlink1 = new UIItemHyperlink1(this);
                }
                return this.mUIItemHyperlink1;
            }
        }
        
        public UIItemCell1 UIItemCell1
        {
            get
            {
                if ((this.mUIItemCell1 == null))
                {
                    this.mUIItemCell1 = new UIItemCell1(this);
                }
                return this.mUIItemCell1;
            }
        }
        
        public UIItemHyperlink2 UIItemHyperlink2
        {
            get
            {
                if ((this.mUIItemHyperlink2 == null))
                {
                    this.mUIItemHyperlink2 = new UIItemHyperlink2(this);
                }
                return this.mUIItemHyperlink2;
            }
        }
        
        public UIItemHyperlink3 UIItemHyperlink3
        {
            get
            {
                if ((this.mUIItemHyperlink3 == null))
                {
                    this.mUIItemHyperlink3 = new UIItemHyperlink3(this);
                }
                return this.mUIItemHyperlink3;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIItem4ОшибкиприпроведListItem UIItem4ОшибкиприпроведListItem
        {
            get
            {
                if ((this.mUIItem4ОшибкиприпроведListItem == null))
                {
                    this.mUIItem4ОшибкиприпроведListItem = new UIItem4ОшибкиприпроведListItem(this);
                }
                return this.mUIItem4ОшибкиприпроведListItem;
            }
        }
        
        public UIItemCell2 UIItemCell2
        {
            get
            {
                if ((this.mUIItemCell2 == null))
                {
                    this.mUIItemCell2 = new UIItemCell2(this);
                }
                return this.mUIItemCell2;
            }
        }
        
        public UIItem427НедостаткиоргHyperlink UIItem427НедостаткиоргHyperlink
        {
            get
            {
                if ((this.mUIItem427НедостаткиоргHyperlink == null))
                {
                    this.mUIItem427НедостаткиоргHyperlink = new UIItem427НедостаткиоргHyperlink(this);
                }
                return this.mUIItem427НедостаткиоргHyperlink;
            }
        }
        
        public UIItemCell3 UIItemCell3
        {
            get
            {
                if ((this.mUIItemCell3 == null))
                {
                    this.mUIItemCell3 = new UIItemCell3(this);
                }
                return this.mUIItemCell3;
            }
        }
        
        public UIПотериListItem UIПотериListItem
        {
            get
            {
                if ((this.mUIПотериListItem == null))
                {
                    this.mUIПотериListItem = new UIПотериListItem(this);
                }
                return this.mUIПотериListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIItemComboBox mUIItemComboBox;
        
        private UIItemHyperlink mUIItemHyperlink;
        
        private UIItem11Hyperlink mUIItem11Hyperlink;
        
        private UIItemCell mUIItemCell;
        
        private UIItemHyperlink1 mUIItemHyperlink1;
        
        private UIItemCell1 mUIItemCell1;
        
        private UIItemHyperlink2 mUIItemHyperlink2;
        
        private UIItemHyperlink3 mUIItemHyperlink3;
        
        private UIItemTable mUIItemTable;
        
        private WinCustom mUIItemCustom;
        
        private UIItem4ОшибкиприпроведListItem mUIItem4ОшибкиприпроведListItem;
        
        private UIItemCell2 mUIItemCell2;
        
        private UIItem427НедостаткиоргHyperlink mUIItem427НедостаткиоргHyperlink;
        
        private UIItemCell3 mUIItemCell3;
        
        private UIПотериListItem mUIПотериListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemComboBox : WinComboBox
    {
        
        public UIItemComboBox(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIВведитепоисковыйзапрEdit
        {
            get
            {
                if ((this.mUIВведитепоисковыйзапрEdit == null))
                {
                    this.mUIВведитепоисковыйзапрEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIВведитепоисковыйзапрEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Введите поисковый запрос или адрес";
                    this.mUIВведитепоисковыйзапрEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIВведитепоисковыйзапрEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIВведитепоисковыйзапрEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemHyperlink : WinHyperlink
    {
        
        public UIItemHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "...";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem11Hyperlink : WinHyperlink
    {
        
        public UIItem11Hyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "11";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItem11Edit
        {
            get
            {
                if ((this.mUIItem11Edit == null))
                {
                    this.mUIItem11Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItem11Edit.SearchProperties[WinEdit.PropertyNames.Name] = "11";
                    this.mUIItem11Edit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItem11Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItem11Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCell : WinCell
    {
        
        public UIItemCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemHyperlink1 : WinHyperlink
    {
        
        public UIItemHyperlink1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "...";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[WinEdit.PropertyNames.Name] = "...";
                    this.mUIItemEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCell1 : WinCell
    {
        
        public UIItemCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIДепартаментбезопасноEdit
        {
            get
            {
                if ((this.mUIДепартаментбезопасноEdit == null))
                {
                    this.mUIДепартаментбезопасноEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIДепартаментбезопасноEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Департамент безопасности";
                    this.mUIДепартаментбезопасноEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIДепартаментбезопасноEdit;
            }
        }
        
        public WinEdit UIДепартаментКазначейсEdit
        {
            get
            {
                if ((this.mUIДепартаментКазначейсEdit == null))
                {
                    this.mUIДепартаментКазначейсEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIДепартаментКазначейсEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Департамент Казначейство";
                    this.mUIДепартаментКазначейсEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIДепартаментКазначейсEdit;
            }
        }
        
        public WinCustom UIУральскийРЦCustom
        {
            get
            {
                if ((this.mUIУральскийРЦCustom == null))
                {
                    this.mUIУральскийРЦCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIУральскийРЦCustom.SearchProperties[UITestControl.PropertyNames.Name] = "Уральский РЦ";
                    this.mUIУральскийРЦCustom.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIУральскийРЦCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIДепартаментбезопасноEdit;
        
        private WinEdit mUIДепартаментКазначейсEdit;
        
        private WinCustom mUIУральскийРЦCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemHyperlink2 : WinHyperlink
    {
        
        public UIItemHyperlink2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "...";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[WinEdit.PropertyNames.Name] = "...";
                    this.mUIItemEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemHyperlink3 : WinHyperlink
    {
        
        public UIItemHyperlink3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "...";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[WinEdit.PropertyNames.Name] = "...";
                    this.mUIItemEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable : WinTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIКатегориясобытияОРВыRow UIКатегориясобытияОРВыRow
        {
            get
            {
                if ((this.mUIКатегориясобытияОРВыRow == null))
                {
                    this.mUIКатегориясобытияОРВыRow = new UIКатегориясобытияОРВыRow(this);
                }
                return this.mUIКатегориясобытияОРВыRow;
            }
        }
        #endregion
        
        #region Fields
        private UIКатегориясобытияОРВыRow mUIКатегориясобытияОРВыRow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIКатегориясобытияОРВыRow : WinRow
    {
        
        public UIКатегориясобытияОРВыRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Категория события ОРВыберите значение ...    ";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[WinCell.PropertyNames.Instance] = "2";
                    this.mUIItemCell.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem4ОшибкиприпроведListItem : WinListItem
    {
        
        public UIItem4ОшибкиприпроведListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "4 Ошибки при проведении операций";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UIItem4ОшибкиприпроведHyperlink
        {
            get
            {
                if ((this.mUIItem4ОшибкиприпроведHyperlink == null))
                {
                    this.mUIItem4ОшибкиприпроведHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUIItem4ОшибкиприпроведHyperlink.SearchProperties[WinHyperlink.PropertyNames.Name] = "4 Ошибки при проведении операций";
                    this.mUIItem4ОшибкиприпроведHyperlink.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItem4ОшибкиприпроведHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUIItem4ОшибкиприпроведHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCell2 : WinCell
    {
        
        public UIItemCell2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UIВыберитезначениеHyperlink
        {
            get
            {
                if ((this.mUIВыберитезначениеHyperlink == null))
                {
                    this.mUIВыберитезначениеHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUIВыберитезначениеHyperlink.SearchProperties[WinHyperlink.PropertyNames.Name] = "Выберите значение";
                    this.mUIВыберитезначениеHyperlink.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIВыберитезначениеHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUIВыберитезначениеHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem427НедостаткиоргHyperlink : WinHyperlink
    {
        
        public UIItem427НедостаткиоргHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "4.27 Недостатки организационной структуры/организации внутреннего контроля";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItem427НедостаткиоргEdit
        {
            get
            {
                if ((this.mUIItem427НедостаткиоргEdit == null))
                {
                    this.mUIItem427НедостаткиоргEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItem427НедостаткиоргEdit.SearchProperties[WinEdit.PropertyNames.Name] = "4.27 Недостатки организационной структуры/организации внутреннего контроля";
                    this.mUIItem427НедостаткиоргEdit.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItem427НедостаткиоргEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItem427НедостаткиоргEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCell3 : WinCell
    {
        
        public UIItemCell3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UIВыберитезначениеHyperlink
        {
            get
            {
                if ((this.mUIВыберитезначениеHyperlink == null))
                {
                    this.mUIВыберитезначениеHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUIВыберитезначениеHyperlink.SearchProperties[WinHyperlink.PropertyNames.Name] = "Выберите значение";
                    this.mUIВыберитезначениеHyperlink.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIВыберитезначениеHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUIВыберитезначениеHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIПотериListItem : WinListItem
    {
        
        public UIПотериListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Потери";
            this.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UIПотериHyperlink
        {
            get
            {
                if ((this.mUIПотериHyperlink == null))
                {
                    this.mUIПотериHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUIПотериHyperlink.SearchProperties[WinHyperlink.PropertyNames.Name] = "Потери";
                    this.mUIПотериHyperlink.WindowTitles.Add("MDM.Risks.OperRiskMessageL.SMF.CreateNewMessage - Mozilla Firefox");
                    #endregion
                }
                return this.mUIПотериHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUIПотериHyperlink;
        #endregion
    }
}
